/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/consumer/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia cadastro de consumidor */
        post: operations["registerConsumer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/consumer/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma cadastro do consumidor com OTP */
        post: operations["confirmConsumerRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia cadastro empresarial */
        post: operations["registerCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma OTP e inicia enrolamento TOTP da empresa */
        post: operations["confirmCompanyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reivindica perfil empresarial por CNPJ */
        post: operations["claimCompanyProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/claim/{claimId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompanyClaimStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login via Google SSO */
        post: operations["googleSsoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login via Apple SSO */
        post: operations["appleSsoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria novo caso */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCaseAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia moderação de caso */
        post: operations["startModeration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprova caso em moderação */
        post: operations["approveCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rejeita caso em moderação */
        post: operations["rejectCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/notify-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notifica empresa sobre caso */
        post: operations["notifyCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/company/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Empresa responde ao caso */
        post: operations["companyRespond"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve caso (requer confirmação de ambas as partes) */
        post: operations["resolveCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/close-unresolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fecha caso sem resolução */
        post: operations["closeUnresolved"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export interface webhooks {
    [key: string]: unknown;
}

export interface components {
    schemas: {
        RegisterConsumerRequest: {
            email: string;
            password: string;
            fullName: string;
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        RegisterConfirmRequest: {
            registrationToken: string;
            otp: string;
        };
        RegisterCompanyRequest: {
            email: string;
            password: string;
            cnpj: string;
            legalName: string;
            fullName: string;
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        ClaimCompanyRequest: {
            cnpj: string;
            legalName: string;
            email: string;
            password: string;
            fullName: string;
            documents: components["schemas"]["Document"][];
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        Document: {
            url: string;
            fileName: string;
            mimeType: string;
            sizeBytes: number;
        };
        SsoRequest: {
            idToken: string;
        };
        CreateCaseRequest: {
            companyId: string;
            experienceType: "reclamacao" | "denuncia" | "elogio" | "duvida_resolvida";
            category: "imoveis" | "servicos" | "ecommerce" | "financeiro" | "saude" | "educacao" | "outro";
            description: string;
            occurredAt: string;
            legalAcceptance: components["schemas"]["LegalAcceptance"];
        };
        LegalAcceptance: {
            termId: string;
            contentHashEcho: string;
        };
        ModerationDecisionRequest: {
            justification: string;
        };
        CompanyResponseRequest: {
            response: string;
        };
        RegisterInitResponse: {
            registrationToken: string;
        };
        TokensResponse: {
            accessToken: string;
            refreshToken: string;
        };
        CompanyConfirmResponse: {
            accessToken: string;
            totpSecret: string;
            qrCodeDataUrl: string;
            recoveryCodes: string[];
        };
        ClaimCreatedResponse: {
            claimId: string;
        };
        ClaimStatusResponse: {
            claimId: string;
            status: "pending" | "approved" | "rejected";
        };
        CaseResponse: {
            id: string;
            status: "draft" | "pending_moderation" | "published" | "notified" | "responded" | "resolved" | "closed_unresolved";
            createdAt: string;
        };
        AuditTimelineResponse: components["schemas"]["AuditEvent"][];
        AuditEvent: {
            id: string;
            action: string;
            actor: string;
            timestamp: string;
        };
        Error: {
            code: string;
            message: string;
        };
    };
    responses: {
        BadRequest: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        Unauthorized: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        Forbidden: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        NotFound: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        Conflict: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        UnprocessableEntity: {
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    securitySchemes: never;
}

export interface operations {
    registerConsumer: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConsumerRequest"];
            };
        };
        responses: {
            201: {
                content: {
                    "application/json": components["schemas"]["RegisterInitResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    confirmConsumerRegistration: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConfirmRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    registerCompany: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCompanyRequest"];
            };
        };
        responses: {
            201: {
                content: {
                    "application/json": components["schemas"]["RegisterInitResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    confirmCompanyRegistration: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConfirmRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CompanyConfirmResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    claimCompanyProfile: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCompanyRequest"];
            };
        };
        responses: {
            202: {
                content: {
                    "application/json": components["schemas"]["ClaimCreatedResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCompanyClaimStatus: {
        parameters: {
            path: {
                claimId: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["ClaimStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    googleSsoLogin: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    appleSsoLogin: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCase: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            201: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCase: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCaseAudit: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["AuditTimelineResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startModeration: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    approveCase: {
        parameters: {
            path: {
                id: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationDecisionRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectCase: {
        parameters: {
            path: {
                id: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationDecisionRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    notifyCompany: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    companyRespond: {
        parameters: {
            path: {
                id: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyResponseRequest"];
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    resolveCase: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    closeUnresolved: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}

export interface external {
    never: unknown;
}
